name: Issue Report
description: Something is broken
title: "[Issue]: "
labels: ["issue"]

body:
  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Tell us what happened in a very clear and simple way
      value: Please fill this form with as much information as possible
  - type: textarea
    id: platform
    attributes:
      label: Version Platform Description
      description: Describe your platform (program version, OS, browser)
      value: 
  - type: markdown
    attributes:
      value: |
        Any issues without version information will be closed
        Additionally provide any relevant platorm information (OS, browser, versions)
