name: Issue Report
description: Something is broken
title: "[Issue]: "
labels: ["issue"]

body:
  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Tell us what happened in a very clear and simple way
      value: Please fill this form with as much information as possible
  - type: textarea
    id: platform
    attributes:
      label: Platform Description
      description: Describe your platform (OS, browser, versions)
      value: Please fill this form with as much information as possible
  - type: markdown
    attributes:
      value: Any additional info
